### ISSUE TITLE
p < 0.5

### ISSUE THREAD

**Issue by dirkschumacher** [juliuste/airrohr-prediction#2]
The error probability should always be less than 0.5. We could start with 0.3 and then observe if there are too many alarms.

**Comment by juliuste** [comment]
Shouldn't it be too *few* alarms when we consider the lower boundary?

**Comment by juliuste** [comment]
The referenced commit already fixes this, right?

**Comment by dirkschumacher** [comment]
Yes. Fixed. I would maybe even set it to .95. Yes probably too few. Who knows.
